version: '3'

services:
  web-client:
    build:
      context: ./web-client
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://web-client:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api-server:
    build:
      context: ./api-server
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api-server:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres-db:
    build:
      context: ./postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  custom-net:
    driver: bridge

volumes:
  postgres-data:

